export const futureScenes = [
  {
    id: "orientation",
    sceneNumber: 0,
    title: "Visualization Workbench",
    shortTitle: "Orientation",
    type: "orientation",
    duration: "1 min",
    prompt: "Practice the workbench controls before the design tasks begin.",
    task: "Inspect the figures. Use Next when ready.",
    status: "Orientation: practice the interaction pattern.",
    workbenchTitle: "Interaction rehearsal",
    defaultWorkbench: { stressTestIndex: 0, revealRedesign: false },
  },
  {
    id: "contrast-hierarchy",
    sceneNumber: 2,
    title: "Contrast and Hierarchy",
    shortTitle: "Contrast",
    type: "contrast",
    duration: "2 min",
    prompt: "What information reaches your eye first?",
    task: "Increase the Stress Test, then reveal the redesign.",
    status: "Scene 2: contrast and hierarchy.",
    workbenchTitle: "Priority areas and supporting context",
    defaultWorkbench: { stressTestIndex: 0, revealRedesign: false },
    reveal: "The redesign separates priority areas, context, and labels.",
  },
  {
    id: "robust-comparison",
    sceneNumber: 3,
    title: "Robust Design Comparison",
    shortTitle: "Rank",
    type: "comparison",
    duration: "3 min",
    prompt: "Rank the three designs from most robust to least robust.",
    task: "Drag the cards into order, then Check.",
    status: "Scene 3: robust design comparison.",
    workbenchTitle: "Ranking bench",
    defaultWorkbench: { stressTestIndex: 3, revealRedesign: true },
  },
  {
    id: "reflection",
    sceneNumber: 4,
    title: "Course Reflection",
    shortTitle: "Close",
    type: "reflection",
    duration: "1 min",
    prompt: "Complete the reflection in the course tool after leaving the prototype.",
    task: "This app does not collect responses.",
    status: "Scene 4: external course reflection.",
    workbenchTitle: "Course handoff",
    defaultWorkbench: { stressTestIndex: 0, revealRedesign: true },
  },
];
